services:

### APPLICATION PART

  postgresdb:
    image: ${POSTGRES_IMAGE}
    networks:
      - todonet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb

  todobackend-springboot:
    image: ghcr.io/lftraining/lfs148-code-todobackend-springboot:v2404
    networks:
      - todonet
    build:
      context: ./todobackend-springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OTEL_SERVICE_NAME=todobackend-springboot
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=otlp,logging-otlp
      - OTEL_LOGS_EXPORTER=otlp
    depends_on:
      - postgresdb

  todoui-thymeleaf:
    image: ghcr.io/lftraining/lfs148-code-todoui-thymeleaf:v2404
    build:
      context: ./todoui-thymeleaf
      dockerfile: Dockerfile #-multistage
    networks:
      - todonet
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://todobackend-springboot:8080/
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=todoui-thymeleaf
      - OTEL_METRICS_EXPORTER=otlp,logging-otlp
      - OTEL_LOGS_EXPORTER=otlp

  todoui-flask:
    image: ghcr.io/lftraining/lfs148-code-todoui-flask:v2404
    build:
      context: ./todoui-flask
    networks:
      - todonet
    ports:
      - "5001:5000"
    environment:
      - BACKEND_URL=http://todobackend-springboot:8080/todos/
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=todoui-flask
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

  loadgenerator:
    image: ghcr.io/lftraining/lfs148-code-simple-generator:v2404
    build:
      context: ./loadgenerator
    networks:
      - todonet


### OTEL PART

  # jaegercol:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "16686:16686"
  #     - "4317:4317"

  otelcol:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./collector/otel-collector-config-lgtm.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
      - todonet

  grafana:
    image: grafana/grafana:12.3.1
    volumes:
      - "./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
    #  - "./grafana:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - todonet

  prometheus:
    image: quay.io/prometheus/prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-otlp-receiver
      - --web.enable-remote-write-receiver
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus/prometheus-config-lgtm.yaml:/etc/prometheus/prometheus-config.yaml
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - todonet

  tempo:
    image: grafana/tempo:2.9.0
    ports:
      - "3200:3200"
      - "55680:55680"
      - "55681:55681"
      - "14250:14250"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./grafana/tempo.yaml:/etc/tempo.yaml"
    networks:
      - todonet

  loki:
    image: grafana/loki:3.6.3
    command: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - "./grafana/loki.yaml:/etc/loki/loki.yaml"
    networks:
      - todonet

  pyroscope:
    image: grafana/pyroscope:1.16.2
    ports:
      - "4040:4040"
    command: ["server"]
    networks:
      - todonet


networks:
  todonet: