apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-gen-store
  namespace: facts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-gen-store
  template:
    metadata:
      labels:
        app: image-gen-store
    spec:
      containers:
        - name: image-gen-store
          image: $IMAGE_GEN_STORE_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVICE_URL
              value: $DB_SERVICE_URL
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_SERVICE_NAME
              value: image-gen-store

# TODO: switch password etc to secrets